# https://gist.github.com/harmittaa/7d3c51041ffd0e54cda9807e95593309
# https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4
# https://docs.travis-ci.com/user/languages/android/

language: android
sudo: required
jdk: oraclejdk8

before_install:
- yes | sdkmanager "platforms;android-28"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=28
  - ANDROID_BUILD_TOOLS=28.0.2
  - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API
  - extra
  - tools
  - platform-tools
  - tools
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

script:
- "./gradlew clean test"
